<a href="https://colab.research.google.com/github/electropavuk/nn/blob/master/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Лабораторна робота №2 з дисципліни "Нейронні мережі"
### студента групи КН-31/2
### Маурін Андрій
#### Варіант №4

In [1]:
import numpy as np
import tensorflow as tf

За матеріалами [2] ознайомитись із засадами бібліотеки TensorFlow:
- засвоєння поняття тензору
- знати різні способи створення тензорів
- створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)
- продемонструвати основні математичні операції над тензорами
- провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame)


In [7]:
data = np.random.uniform(0, 10, (5, 7)).astype(int)
tensor = tf.convert_to_tensor(data)
print(tensor)

tf.Tensor(
[[1 7 5 8 9 1 1]
 [0 7 9 7 6 9 9]
 [3 6 6 6 9 9 7]
 [1 2 3 8 1 6 2]
 [6 0 7 7 3 9 7]], shape=(5, 7), dtype=int64)


In [12]:
print(f'tensor: {tensor.shape}')
print(f'rank: {tf.rank(tensor)}')
print(f'size: {tf.size(tensor)}')

tensor: (5, 7)
rank: 2
size: 35


In [19]:
print(tf.linalg.matmul(tensor, tensor, transpose_b=True))
print(tf.math.reduce_sum(tensor, axis=1))
print(tf.concat([tensor, tensor], axis=0))
print(tensor + 10)
print(tensor * 10)

tf.Tensor(
[[222 222 220 111 140]
 [222 377 336 175 274]
 [220 336 328 158 259]
 [111 175 158 119 154]
 [140 274 259 154 273]], shape=(5, 5), dtype=int64)
tf.Tensor([32 47 46 23 39], shape=(5,), dtype=int64)
tf.Tensor(
[[1 7 5 8 9 1 1]
 [0 7 9 7 6 9 9]
 [3 6 6 6 9 9 7]
 [1 2 3 8 1 6 2]
 [6 0 7 7 3 9 7]
 [1 7 5 8 9 1 1]
 [0 7 9 7 6 9 9]
 [3 6 6 6 9 9 7]
 [1 2 3 8 1 6 2]
 [6 0 7 7 3 9 7]], shape=(10, 7), dtype=int64)
tf.Tensor(
[[11 17 15 18 19 11 11]
 [10 17 19 17 16 19 19]
 [13 16 16 16 19 19 17]
 [11 12 13 18 11 16 12]
 [16 10 17 17 13 19 17]], shape=(5, 7), dtype=int64)
tf.Tensor(
[[10 70 50 80 90 10 10]
 [ 0 70 90 70 60 90 90]
 [30 60 60 60 90 90 70]
 [10 20 30 80 10 60 20]
 [60  0 70 70 30 90 70]], shape=(5, 7), dtype=int64)
